"""empty message

Revision ID: 30b8ff556660
Revises: 416b14d7c752
Create Date: 2018-08-22 10:57:47.318396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b8ff556660'
down_revision = '416b14d7c752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks2deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('deliverable', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['deliverable'], ['deliverables.code'], ),
    sa.ForeignKeyConstraint(['task'], ['tasks.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task', 'deliverable', name='_task_deliverable_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks2deliverables')
    # ### end Alembic commands ###
